const films = [
    {
        id: 0,
        title:" Бунтівний місяць: Частина друга — Та, що лишає шрами",
        year: 2024,
        genre: "Драма",
        image: "https://uaserials.pro/posters/8629.jpg",
    },
    {
        id: 1,
        title: "Мадам Павутина",
        year: 2024,
        genre: " Фантастика",
        image: "https://uaserials.pro/posters/8536.jpg",
    },
    {
        id: 2,
        title: "Сам удома",
        year: 1990,
        genre: " Комедія",
        image: "https://uaserials.pro/posters/1693.jpg",
    },
    {
        id: 3,
        title: "Сіссі — юність імператриці",
        year: 1956,
        genre: " Драма",
        image: "https://uaserials.pro/posters/7330.jpg",
    },
    {
        id: 4,
        title: "Різдвяна ескапада",
        year: 2017,
        genre: "Комедія",
        image: "https://uaserials.pro/posters/8354.jpg",
    },
    {
        id: 5,
        title: "Серце дракона: Битва за вогняне серце",
        year: 2017,
        genre: "Фентезі",
        image: "https://uaserials.pro/posters/6898.jpg",
    },
    {
        id: 6,
        title: "Прогулянка Римом",
        year: 2017,
        genre: "Пригоди",
        image: "https://uaserials.pro/posters/3721.jpg",
    },
    {
        id: 7,
        title: "Готель на свята",
        year: 2022,
        genre: "Комедія",
        image: "https://uaserials.pro/posters/8382.jpg",
    },
    {
        id: 8,
        title: "Отець Стю",
        year: 2022,
        genre: "Драма",
        image: "https://uaserials.pro/posters/8357.jpg",
    },
    {
        id: 9,
        title: "Капітан Америка",
        year: 1990,
        genre:"Фантастика" ,
        image: "https://uaserials.pro/posters/7234.jpg",
    },
]
export default films;